//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apply
    {
        public int ApplyID { get; set; }
        public string ApplyName { get; set; }
        public int JobFindID { get; set; }
        public int JobPostID { get; set; }
    
        public virtual JobFinder JobFinder { get; set; }
        public virtual JobPoster JobPoster { get; set; }
    }
}
