//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DevProjectEntities : DbContext
    {
        public DevProjectEntities()
            : base("name=DevProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adminn> Adminns { get; set; }
        public virtual DbSet<Apply> Applies { get; set; }
        public virtual DbSet<JobFinder> JobFinders { get; set; }
        public virtual DbSet<JobPoster> JobPosters { get; set; }
        public virtual DbSet<Support> Supports { get; set; }
    }
}
